<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>7761508c-0739-4100-a57d-b868cfa95524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='policy']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98a12fae-8328-44b3-96df-e2b8da9982fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>폴리시</value>
      <webElementGuid>6584a65d-6aad-4f70-880a-18e81f963a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;functions&quot;)/li[@id=&quot;policy&quot;]/a[1]</value>
      <webElementGuid>3829ddf5-fc2c-4051-8e52-f776c6194a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='policy']/a</value>
      <webElementGuid>d91a005a-3346-4e34-a562-1e0ea8c05c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'폴리시')]</value>
      <webElementGuid>c821cb21-c0c7-4294-8edd-f763783a3480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='참석자'])[1]/following::a[1]</value>
      <webElementGuid>21ba6963-9a13-40a8-9675-8816f41bf81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='보고서'])[1]/following::a[2]</value>
      <webElementGuid>887add9c-d6b1-40ca-bd85-ba551a1573ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지정 안함'])[1]/preceding::a[1]</value>
      <webElementGuid>69c291e1-3f0f-4f20-95d2-3cd38718b454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/preceding::a[1]</value>
      <webElementGuid>a0256666-4cec-4411-950e-45441dc6829d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='폴리시']/parent::*</value>
      <webElementGuid>9d229b6e-bac3-4d9a-91dc-4b3b9af24b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>86af6521-6b3a-4e93-94ae-cf9ac94f2c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '폴리시' or . = '폴리시')]</value>
      <webElementGuid>5d732eb7-1f11-4749-a3c2-867ce8a1b9da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
