<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>45166eb0-9dc5-4d91-843a-3d895d70a76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-list.log-out > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='user-menu-profile-dropdown']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc64be83-f1d7-42a2-a02f-fcaafb060092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그아웃</value>
      <webElementGuid>91a48bd8-88a1-43e7-8d12-de8660a8238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu-profile-dropdown&quot;)/li[@class=&quot;menu-list log-out&quot;]/a[1]</value>
      <webElementGuid>07a709e5-e082-4d6a-a466-acafd52c3c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='user-menu-profile-dropdown']/li[4]/a</value>
      <webElementGuid>6b632412-74a8-4f7b-b82b-a23aa865d304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그아웃')]</value>
      <webElementGuid>71cf0051-e708-4788-9373-78fda91eda5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업설정'])[1]/following::a[1]</value>
      <webElementGuid>0dd3c55f-d442-4081-880c-a60b95917b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인설정'])[1]/following::a[2]</value>
      <webElementGuid>d3dab59e-b37c-49a8-bf0b-4b31b9d333eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로그아웃']/parent::*</value>
      <webElementGuid>ff4f5689-c1da-4891-95df-1ef7a6f470f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>4c00fe4d-839c-439b-acff-25406408b680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '로그아웃' or . = '로그아웃')]</value>
      <webElementGuid>e160bd72-0eb3-4b74-990b-e452a639ab40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
