<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-k_8cd130</name>
   <tag></tag>
   <elementGuidId>5f8f808a-5abd-47c0-a1e6-774399543f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-dwcupg.iXwwWk.sc-jtHLbV.dJbnRe.sc-kiYsuf.kWhXfq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='profile']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0a2a49e-22c9-4d99-ae2b-23d9afa14135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png</value>
      <webElementGuid>3ff68f0b-1504-451a-b908-f7ee1b03028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ae76501a-3a14-42e7-b7b4-0fc7e5680eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c638cff5-d81c-4177-b689-d55d282b4ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq</value>
      <webElementGuid>c87fa6f8-539c-41fb-b6d5-ecdbe782e68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/img[@class=&quot;sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq&quot;]</value>
      <webElementGuid>ef3d1ce7-dca0-4f05-ac7c-c776bb8a5666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='profile']/img</value>
      <webElementGuid>eb84aa06-185e-42a3-ad3f-de7831fadb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png')]</value>
      <webElementGuid>c26f3b7d-09df-49b3-9c05-e6bdf65e2aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/img</value>
      <webElementGuid>59ae439b-f4e5-4993-8b50-b9f479fa62aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png']</value>
      <webElementGuid>dcfc9142-1818-402f-b7e4-bf8065401c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
