<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>778dfb7a-0439-400e-876f-5c6da6752cb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='policy']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92142c08-b0e1-403c-9150-d866596112e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>폴리시</value>
      <webElementGuid>73168a78-3a2c-435b-9841-ed6db0755c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;functions&quot;)/li[@id=&quot;policy&quot;]/a[1]</value>
      <webElementGuid>7d193d2a-fddd-46b8-b449-32671021b00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='policy']/a</value>
      <webElementGuid>41721f49-edeb-4ec3-b332-4344957183fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'폴리시')]</value>
      <webElementGuid>3f9de556-da8d-40e3-877c-f4fefc2d0bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='참석자'])[1]/following::a[1]</value>
      <webElementGuid>0375336a-fa66-4c90-996d-0ed87e7b28e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='보고서'])[1]/following::a[2]</value>
      <webElementGuid>d8886711-6fba-48bd-af78-9791fae15f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지정 안함'])[1]/preceding::a[1]</value>
      <webElementGuid>92f11544-d91b-4c5e-9c60-ac48720019b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/preceding::a[1]</value>
      <webElementGuid>5dd5a20d-c2a8-4a2e-885b-8f8b3a98ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='폴리시']/parent::*</value>
      <webElementGuid>68fcee70-05ba-474f-9bc1-5d8eb8415585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>1162ddaf-130a-4b26-9464-60257de22294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '폴리시' or . = '폴리시')]</value>
      <webElementGuid>b586a0bd-9391-40b1-990f-2865dc02cdba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
