<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>e27d835d-7d7f-469b-affc-3098c1ba8f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBQB.sc-gsTEea.sc-kTaRPZ.jaHJyk.lhYGXp.kyZtHL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>645e3d85-ab4e-44db-82d7-ff951fea8069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>02ca66f3-846f-4d74-b0bc-c027c8c8a6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBQB sc-gsTEea sc-kTaRPZ jaHJyk lhYGXp kyZtHL</value>
      <webElementGuid>d0c989fc-bf04-4f3b-9d7e-4c0666753cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>e645b8e7-e995-4d1b-9b41-d109fba52154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fnlXEO kyUQzC&quot;]/div[@class=&quot;sc-jfJyPD jIxhWS&quot;]/div[@class=&quot;sc-jYCGPb gVhugJ&quot;]/form[@class=&quot;sc-hlWxgi ceLMGk sc-bKNxrx fwHqDW&quot;]/button[@class=&quot;sc-bdfBQB sc-gsTEea sc-kTaRPZ jaHJyk lhYGXp kyZtHL&quot;]</value>
      <webElementGuid>77132a9c-4491-4796-92d2-5fdb1d961067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>307bdb36-aa1a-4497-8ceb-ebad45d31f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/button</value>
      <webElementGuid>910fc33d-60f0-462c-8eeb-da7c902c54fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='비밀번호 찾기'])[1]/following::button[1]</value>
      <webElementGuid>82311fad-2c05-407e-96a8-8be2883b89c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='비밀번호'])[1]/following::button[3]</value>
      <webElementGuid>a8d814b2-6681-471a-8bc2-9af78d0555d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Login (SSO)'])[1]/preceding::button[1]</value>
      <webElementGuid>5ea1a243-f03b-4f40-b6df-69f55cd8ba89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='회원가입'])[1]/preceding::button[1]</value>
      <webElementGuid>7f866e33-7e98-402a-9ff9-448efd0f4888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>e7f97cf7-bd50-4c4a-876c-b84dd4e889cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>e674ffe9-1f6e-48b2-9724-04dff08dfb7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
