<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__policy_name</name>
   <tag></tag>
   <elementGuidId>5de94fe0-9833-4570-a6c3-5e6baf1a63ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='policy_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d5e27e1-71ce-4c70-afee-6e0e89e03d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fbNZge eicyGS sc-bXDkGd gzUuKj</value>
      <webElementGuid>99d6a13b-43d2-4cae-8050-658282d9436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policy_name</value>
      <webElementGuid>05173e19-2d78-4c52-9668-6b1421b43100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ff44077-da39-45a2-ac65-25f424e85e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>New policy - 2023.07.10 (10)</value>
      <webElementGuid>cec17302-e304-4b77-b991-cd92010ef94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy_name&quot;)</value>
      <webElementGuid>f5e921a8-9b5a-4518-abaa-2de1af65d889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='policy_name']</value>
      <webElementGuid>7de4ebf6-5008-4df5-ade3-84bd16bc7596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form/section/div/div/input</value>
      <webElementGuid>9425869f-3055-47b8-846f-6e3d81037f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7f78ea62-0472-4820-9159-4c5bf0d40187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'policy_name' and @type = 'text']</value>
      <webElementGuid>a94a35f8-aab7-4c5e-8fef-dee69347d134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
