<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>04895e64-d456-4a6f-8cf0-7aeae6edff5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='policy']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d556fa20-535b-411c-bdcb-56f0b4daf6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>폴리시</value>
      <webElementGuid>2ab9119e-79d0-4e68-8dbf-2f394a676f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;functions&quot;)/li[@id=&quot;policy&quot;]/a[1]</value>
      <webElementGuid>37f86ae0-1b10-4447-963c-55d4fe9663d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='policy']/a</value>
      <webElementGuid>b631debb-9c1b-41e9-8a2a-8d8d2a7de928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'폴리시')]</value>
      <webElementGuid>491744d6-b585-405a-9793-0fdd7a0c6320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='참석자'])[1]/following::a[1]</value>
      <webElementGuid>1ef8afd9-97fb-48bf-af1e-a703d49bff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='보고서'])[1]/following::a[2]</value>
      <webElementGuid>197ab16e-cd9d-4cf9-84d3-0e1dc4cb2d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지정 안함'])[1]/preceding::a[1]</value>
      <webElementGuid>e26a4e8c-6492-47c2-8d91-8980cd945201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/preceding::a[1]</value>
      <webElementGuid>c2703025-4eed-4a1b-bc19-36f2487bda80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='폴리시']/parent::*</value>
      <webElementGuid>4a559c37-1075-4091-ac11-ab76f22f06cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>221f89da-53fe-43e3-9eb8-ac87c54b5a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '폴리시' or . = '폴리시')]</value>
      <webElementGuid>c3aeb864-8520-411e-89a3-dc379f8c28ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
