<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>2fedc7cc-80cf-4320-9eca-52c6e58264bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBQB.sc-gsTEea.sc-jFEWv.jaHJyk.dqsTYO.fZHxOx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '폴리시 삭제' or . = '폴리시 삭제')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8659eb69-5983-4b58-97f1-75a8a8d1e65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>498f9996-a558-4b8a-a905-69d8ddb999ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c047aed-cf7d-482e-9328-c629288e5259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBQB sc-gsTEea sc-jFEWv jaHJyk dqsTYO fZHxOx</value>
      <webElementGuid>7e280cef-a0ab-450f-ad29-719e424f828d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>폴리시 삭제</value>
      <webElementGuid>d73eaf67-e38e-4fb6-89ac-bc9c22daacd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-container&quot;)/div[@class=&quot;sc-pGacB ieaXHU spendit-modal-container&quot;]/div[@class=&quot;sc-fubCzh ejlNuV&quot;]/footer[@class=&quot;sc-aemIz fdCOst&quot;]/div[1]/div[@class=&quot;sc-hKgJUU leSrJV&quot;]/button[@class=&quot;sc-bdfBQB sc-gsTEea sc-jFEWv jaHJyk dqsTYO fZHxOx&quot;]</value>
      <webElementGuid>1942a001-838d-4cda-a4b9-79f54ac7d6c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>807ea818-0761-4fce-99d0-faae3af981a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-container']/div[2]/div/footer/div/div/button[2]</value>
      <webElementGuid>2ac92421-e2c9-4d71-80ff-0a0c7ab21806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::button[1]</value>
      <webElementGuid>a2cc9271-c4ec-46a0-9aa7-368841e43680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='예, 폴리시를 영구 삭제합니다.'])[1]/following::button[2]</value>
      <webElementGuid>17bd0700-48ac-4610-a000-d7387f8fe676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/button[2]</value>
      <webElementGuid>b77ddc36-1211-4f70-8990-a945802ef250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '폴리시 삭제' or . = '폴리시 삭제')]</value>
      <webElementGuid>47842969-c04c-4e97-a388-ea76be1e543e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>86f6247b-93e0-4569-a582-0295692b29f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
