<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Corporate_icon-trash-gray</name>
   <tag></tag>
   <elementGuidId>c4fc9411-a69e-4b5e-a290-86fc0e3cb317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-trash-gray</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy']/div/section/div[2]/div[2]/div/div[2]/div/div[4]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6e15fc3-3b74-4522-bbd2-146cb7fe9bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash-gray</value>
      <webElementGuid>7661930b-a2dd-4c71-bf43-b321b2b4be50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kmATbt gfIwBy&quot;]/div[@id=&quot;policy&quot;]/div[@class=&quot;sc-giImIA eNzKXM spendit-container&quot;]/section[@class=&quot;sc-cxFLGX kDTybV main&quot;]/div[@class=&quot;sc-dIUeWJ sc-fGPjCt icHBPZ gQfwdh&quot;]/div[@class=&quot;sc-hWiVVa kOhdHG&quot;]/div[@class=&quot;sc-eFuaqX hnTXOO&quot;]/div[@class=&quot;sc-jXktde bueyY&quot;]/div[@class=&quot;sc-fXoxaI jDZndW policy-row&quot;]/div[@class=&quot;sc-bQdRvg bOiPlJ policy-td-4&quot;]/div[@class=&quot;sc-bqyKOL gdREKI icon-row&quot;]/div[@class=&quot;icon-trash-gray&quot;]</value>
      <webElementGuid>e77b9ec7-3b1f-4c9a-add9-a31291ac028c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy']/div/section/div[2]/div[2]/div/div[2]/div/div[4]/div/div[4]</value>
      <webElementGuid>1b7ba82b-642e-46f2-9494-8f7bd3b2fe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]</value>
      <webElementGuid>5fba8084-b3d1-4915-8453-b96d025d477c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
