<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-k_8cd130</name>
   <tag></tag>
   <elementGuidId>3934f458-01d0-480f-8cce-c503f1ff9572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-dwcupg.iXwwWk.sc-jtHLbV.dJbnRe.sc-kiYsuf.kWhXfq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='profile']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>44fe4717-58d2-4d0f-8606-4bf6c95f993a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png</value>
      <webElementGuid>109b4ec1-88a7-4aee-8299-accbf336d995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7bf137ee-d215-4510-89a4-c87aba9a47d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>125b414c-4bd9-40e6-8c76-0cb84f5b74fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq</value>
      <webElementGuid>06699382-4984-4009-bb95-c826f17ac608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/img[@class=&quot;sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq&quot;]</value>
      <webElementGuid>6005f2d8-b1cc-46e6-be72-c8f630e2441c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='profile']/img</value>
      <webElementGuid>1bdbc17d-3e65-48c6-b9f1-5f4a62175a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png')]</value>
      <webElementGuid>ffb178ff-a885-4870-9ecc-d8dd61250c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/img</value>
      <webElementGuid>0b8100d5-3f96-42d0-a2ca-8503edc18404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png']</value>
      <webElementGuid>4290f02e-00fe-43a9-8a2f-63c89834e6fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
