<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>1ff13038-12b1-46c1-b5fd-59ce4e04a98f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='policy']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '폴리시' or . = '폴리시')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3388a33-9c40-4e0e-869f-4afe3f2dcda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>폴리시</value>
      <webElementGuid>d6290c69-71e7-40d1-8167-89e34091479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;functions&quot;)/li[@id=&quot;policy&quot;]/a[1]</value>
      <webElementGuid>7e5cbe6a-f297-4b8b-ab9d-71129ad9f1ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='policy']/a</value>
      <webElementGuid>d7be4e61-6292-47c6-8472-62f9c65f2b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'폴리시')]</value>
      <webElementGuid>0f897ccc-b221-420b-8592-48e0b68592bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='참석자'])[1]/following::a[1]</value>
      <webElementGuid>7e47288c-ee18-4745-8831-e5e739d200d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='보고서'])[1]/following::a[2]</value>
      <webElementGuid>2aa6f4ed-0bb9-4f1a-8a52-8a2ce4a604fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지정 안함'])[1]/preceding::a[1]</value>
      <webElementGuid>50373ada-be5f-464d-83d5-e7435cccb8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/preceding::a[1]</value>
      <webElementGuid>d57a9a91-e7b0-4573-8656-864d6810b06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='폴리시']/parent::*</value>
      <webElementGuid>bebbaad4-6504-40dd-b591-570482361b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>00c96cc0-d905-457a-a382-e1e42b1a645a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '폴리시' or . = '폴리시')]</value>
      <webElementGuid>5760590e-a6c7-4123-91ab-26ad35371983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
