<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>5ccf89e1-7c6d-4490-bdd7-a66c360f60b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-list.log-out > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='user-menu-profile-dropdown']/li[4]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '로그아웃' or . = '로그아웃')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db79eb24-e90a-47ac-9823-90b08b9cca57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그아웃</value>
      <webElementGuid>859eb77a-afdc-458d-878e-a061f64984e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu-profile-dropdown&quot;)/li[@class=&quot;menu-list log-out&quot;]/a[1]</value>
      <webElementGuid>3fa080e7-05c8-4086-b675-1a689c41267e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='user-menu-profile-dropdown']/li[4]/a</value>
      <webElementGuid>22c9791d-57a9-4f47-9653-0a45c07c0b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그아웃')]</value>
      <webElementGuid>d318876d-b303-4ff0-8b39-238fa996682f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업설정'])[1]/following::a[1]</value>
      <webElementGuid>9e6f328a-354a-4542-af31-4575c0ed163a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인설정'])[1]/following::a[2]</value>
      <webElementGuid>a4466895-c40b-4487-b37f-5d77306e2b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로그아웃']/parent::*</value>
      <webElementGuid>b4ade229-c761-48a5-9fd0-66a0bf977c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>054f6016-3bfc-4678-a76f-06f2c9dbe552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '로그아웃' or . = '로그아웃')]</value>
      <webElementGuid>1b6846bf-7a05-4497-acd4-04174e8e7850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
