<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>c6b8e0cb-65d0-4131-86d7-2a36275f4eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBQB.sc-gsTEea.sc-jlIlqL.jaHJyk.lhYGXp.bYjanT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fa5f75a-99e6-4605-84e0-6e61a685c61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b41b9aab-6417-468e-b757-0cb2d987a30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBQB sc-gsTEea sc-jlIlqL jaHJyk lhYGXp bYjanT</value>
      <webElementGuid>6a562204-7c85-4afb-ae5b-bfa50a105bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>저장</value>
      <webElementGuid>af2aa66f-499b-4664-90ea-046d08dd215e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-info&quot;)/div[@class=&quot;sc-giImIA eNzKXM spendit-container&quot;]/section[@class=&quot;sc-cxFLGX kDTybV detail&quot;]/div[@class=&quot;sc-dIUeWJ sc-lmyUgd jZJFjf cBOibT&quot;]/div[@class=&quot;sc-idOiZg bEkbKy&quot;]/form[@class=&quot;sc-iWRHom fwewlo&quot;]/button[@class=&quot;sc-bdfBQB sc-gsTEea sc-jlIlqL jaHJyk lhYGXp bYjanT&quot;]</value>
      <webElementGuid>fa123276-a1e7-4ada-b7cd-0655cd4d1107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2b66d98a-4172-49eb-825e-8f2d294b58da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form[3]/button</value>
      <webElementGuid>12ece5d9-68e6-411b-8644-8d1a5da1b1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='금액 절삭'])[1]/following::button[1]</value>
      <webElementGuid>7c9c6660-3bf4-4983-b42e-46311d1bff9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='거리 공제'])[1]/following::button[1]</value>
      <webElementGuid>86be7dfe-1b9b-4111-b617-bd712eb605b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지출 한도 설정'])[1]/preceding::button[1]</value>
      <webElementGuid>0a2621da-e2ec-44d0-ab28-71c0382e2920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='지출 최대 한도 체크'])[1]/preceding::button[1]</value>
      <webElementGuid>efcec7ae-b324-4516-b4f8-87d602d37046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='저장']/parent::*</value>
      <webElementGuid>46c6bab4-c4df-413f-83a9-54a357eb1061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/button</value>
      <webElementGuid>cbf0f028-eb93-4155-8875-7dace374bc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '저장' or . = '저장')]</value>
      <webElementGuid>8100cf7c-eed1-4427-9e57-db9397de36c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
