<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>fbd426a2-f934-4f2b-87a8-806cc9c0bcde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBQB.sc-gsTEea.sc-kOtXPA.jaHJyk.lhYGXp.hmSnXY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '저장' or . = '저장')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77367edf-1790-45fb-b535-9e8661297bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad0f8cf2-cdde-43d1-adcd-db19e53f2fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBQB sc-gsTEea sc-kOtXPA jaHJyk lhYGXp hmSnXY</value>
      <webElementGuid>5b7c4d44-ec66-4518-b291-686506218b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>저장</value>
      <webElementGuid>963a1baf-d9f5-4f6b-afc0-5c2d5c93e870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-info&quot;)/div[@class=&quot;sc-giImIA eNzKXM spendit-container&quot;]/section[@class=&quot;sc-cxFLGX kDTybV detail&quot;]/div[@class=&quot;sc-pGacB ieaXHU spendit-modal-container&quot;]/div[@class=&quot;sc-fubCzh ejlNuV&quot;]/footer[@class=&quot;sc-aemIz fdCOst&quot;]/div[1]/div[@class=&quot;sc-hKgJUU leSrJV&quot;]/button[@class=&quot;sc-bdfBQB sc-gsTEea sc-kOtXPA jaHJyk lhYGXp hmSnXY&quot;]</value>
      <webElementGuid>d4fd3acc-9049-413d-945f-1d291e93ff65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>29c9c79f-d729-4686-987f-16e45119fe58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div[2]/div/footer/div/div/button[2]</value>
      <webElementGuid>d35732a6-61e4-4c94-99f9-9929b9f37ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::button[1]</value>
      <webElementGuid>aab1bc32-e9ef-44cd-afc0-615ea69a478d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='패스트트랙'])[3]/following::button[2]</value>
      <webElementGuid>f8cfd483-a0d8-417e-ba6e-10a374b5b98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dbb4b9c8-c9fe-45b6-adc0-6de558cc89f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '저장' or . = '저장')]</value>
      <webElementGuid>d6352bd2-1b1d-426f-a3c1-dcec3bae7ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
