<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-k_8cd130</name>
   <tag></tag>
   <elementGuidId>87228eff-5f26-4dcb-94c6-9e62e51e7f7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-dwcupg.iXwwWk.sc-jtHLbV.dJbnRe.sc-kiYsuf.kWhXfq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='profile']/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bf19472-7f2f-4243-92f2-84c252f38de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png</value>
      <webElementGuid>d22de00b-a084-4bc4-932b-9cd6c8c687ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2d13bceb-3012-4b43-8309-7e5bb216a821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e1ff2e9a-d697-4878-9847-aa92f3e696f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq</value>
      <webElementGuid>8517aeaf-bc6e-452f-9ee6-08ab65b14574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/img[@class=&quot;sc-dwcupg iXwwWk sc-jtHLbV dJbnRe sc-kiYsuf kWhXfq&quot;]</value>
      <webElementGuid>8adbef37-45e1-498a-8c99-ca92acd2f78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='profile']/img</value>
      <webElementGuid>8d62072f-b957-49ef-bd7d-5c27bc1f40b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png')]</value>
      <webElementGuid>658d03d8-204a-451b-ab3d-26fa7c711a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/img</value>
      <webElementGuid>c8ec538d-2020-47f9-9525-1c2c2c5fc2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s3.ap-northeast-2.amazonaws.com/spendit-bucket-staging/resource/icons/company-tax/profile-default.png']</value>
      <webElementGuid>e7a557c3-af12-4545-ab35-4ae2d8fb1f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
