<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Km_fuel1</name>
   <tag></tag>
   <elementGuidId>8215eb00-9277-4439-bede-9c62bb7da43c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fuel1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fuel1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebca8be1-aee6-4baa-ac6d-5f1e6259db95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fbNZge gnvAhl sc-bXDkGd gzUuKj input </value>
      <webElementGuid>274ea2af-9c71-4cc2-b92c-e397f63a91b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fuel1</value>
      <webElementGuid>fb9d9696-828e-463b-8a0f-6367b7e3b752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-private</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e4d6489-fa2d-4598-a436-7fc078cf04b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0de97eca-efd4-4d13-b11a-2c35ca0e4281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f834b8c4-f0ff-4ec9-b2a7-18b72e7d6853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuel1&quot;)</value>
      <webElementGuid>91ea6ce7-4cb3-4677-831b-5876e85276df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fuel1']</value>
      <webElementGuid>8d29b7e3-1309-40b7-bce8-bed435c785ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form[3]/div/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>f2f6b961-7bbf-43e9-864a-1a3c4a355e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>2e20ff22-48b2-46b2-8d10-c056996a35a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fuel1' and @type = 'text']</value>
      <webElementGuid>d62fbcfd-402b-4ead-b0d8-fafe51942b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
