<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Km_fuel3</name>
   <tag></tag>
   <elementGuidId>73f3b2f4-97d6-406f-a429-419898857fba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fuel3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fuel3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e1ef7f4-56db-49e2-9d56-a039e06dd440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fbNZge gnvAhl sc-bXDkGd gzUuKj input </value>
      <webElementGuid>7420943e-aa45-4b8b-823c-1a43cb820d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fuel3</value>
      <webElementGuid>60eae8e2-ff4f-4f6e-922e-4a2a45e0e6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-private</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc3cdb80-b76a-466f-b2f3-6e3e567f2c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d58492e-b405-4c80-aa5b-e48781e6611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>13cf537f-c06c-4a32-8461-eaac5ca021bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuel3&quot;)</value>
      <webElementGuid>0d3b4c26-cdf0-44c8-8aa2-a1730ec7732d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fuel3']</value>
      <webElementGuid>70a8ac78-878a-4030-8a98-7dd1ae0b552b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form[3]/div/table/tbody/tr[4]/td[3]/input</value>
      <webElementGuid>be5d6aaf-01cd-4925-aa31-e839af8d9f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/input</value>
      <webElementGuid>a98b7522-0114-435e-845e-9e7399822883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fuel3' and @type = 'text']</value>
      <webElementGuid>733d26ab-ca26-4581-a183-ccfa7eb04232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
