<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Km_fuel2</name>
   <tag></tag>
   <elementGuidId>389ca3a5-c374-4534-8896-55398fd4048c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fuel2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fuel2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9423d4b5-85db-458c-99b9-8a010744ee8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fbNZge gnvAhl sc-bXDkGd gzUuKj input </value>
      <webElementGuid>76ae8933-bf99-4bb4-9669-ac5bd3d9553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fuel2</value>
      <webElementGuid>9db5c650-5c71-4830-a836-8d259e6643d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-private</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4f7607a-b849-432f-b249-eebdf4cd551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcf08602-1634-424b-b51c-1c6acfe9eb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07fc28cb-1ee3-42df-9a2a-6d1256db69ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuel2&quot;)</value>
      <webElementGuid>f59f2531-d156-464b-8959-8d3f151f06bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fuel2']</value>
      <webElementGuid>70a26e6a-6d71-48a6-9620-8d7bfa71dbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form[3]/div/table/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>d363ab0f-a38b-4f4d-b04e-6c5d2a63df57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>86596702-f355-4fca-8ae3-487191cbd2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fuel2' and @type = 'text']</value>
      <webElementGuid>5be60abc-0b12-469f-8c12-8c11bece640d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
