<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Km_fuel0</name>
   <tag></tag>
   <elementGuidId>02f5faad-b2b3-41d7-aab0-83d512e282ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fuel0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fuel0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1345b409-7f1a-4fab-9792-a31c5ef10432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fbNZge gnvAhl sc-bXDkGd gzUuKj input </value>
      <webElementGuid>c73b016b-e00d-4de7-ae1b-0d6f03291c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fuel0</value>
      <webElementGuid>28a1c32a-6c5b-4a0b-a291-3b16019ebeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-private</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f31824e-faec-49d5-a16a-6aa0030dc8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8ca9626-e0c8-489e-a490-b9c7eac49746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce472d46-9ce6-4ab2-8378-91f892ff9fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuel0&quot;)</value>
      <webElementGuid>935e7495-f3c2-4462-bac9-87ee2115cc6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fuel0']</value>
      <webElementGuid>b7036dc8-dd51-4cda-8d39-8d7c180ea851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-info']/div/section/div/div/form[3]/div/table/tbody/tr/td[3]/input</value>
      <webElementGuid>69ac94cc-a314-4058-99b1-0c1227d122c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>61e2dabd-8672-4a5f-9cde-bb08b9757263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fuel0' and @type = 'text']</value>
      <webElementGuid>77d30456-fefb-4e5e-872b-8cff7bef3c1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
